data_limit: 10000
data_folder: "data"
squad_dataset_csv: "SquadDataset.csv"
squad_dataset_final_csv: "SquadDatasetFinal.csv"

model_names:
  model: "models/model.h5"
  encoder_model: "models/enc_model.h5"
  decoder_model: "models/dec_model.h5"

interface_settings:
  window_height: 500
  window_width: 1000
  text_field_height_ratio: 20
  text_field_width_ratio: 10
  input_text_field_height_ratio: 10
